from __future__ import annotations

import hmac
import hashlib
import time

from fastapi import Header, HTTPException, WebSocket, status

from config.settings import settings


def _verify_admin_api_key(provided_raw: str | None) -> bool:
    expected = settings.admin_api_key.strip()
    provided = (provided_raw or "").strip()
    return bool(expected and provided and hmac.compare_digest(provided, expected))


def require_admin_api_key(x_api_key: str | None = Header(default=None, alias="X-API-Key")) -> None:
    """
    Enforce admin API key for sensitive endpoints.
    Fail closed when ADMIN_API_KEY is not configured.
    """
    if not settings.admin_api_key.strip():
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="ADMIN_API_KEY is not configured on the server.",
        )
    if not _verify_admin_api_key(x_api_key):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid or missing X-API-Key.",
        )


def require_admin_api_key_ws(websocket: WebSocket) -> bool:
    """
    WebSocket variant: accept API key from header (X-API-Key) or `api_key` query param.
    """
    if not settings.admin_api_key.strip():
        return False
    provided = websocket.headers.get("x-api-key") or websocket.query_params.get("api_key")
    return _verify_admin_api_key(provided)


def create_ws_ticket(run_id: str, ttl_seconds: int = 90) -> str:
    """
    Create a short-lived HMAC ticket for WebSocket auth without exposing ADMIN_API_KEY.
    Ticket format: <exp_ts>:<hex_signature>
    """
    secret = settings.admin_api_key.strip()
    if not secret:
        return ""
    exp_ts = int(time.time()) + max(ttl_seconds, 1)
    payload = f"{run_id}:{exp_ts}".encode("utf-8")
    sig = hmac.new(secret.encode("utf-8"), payload, hashlib.sha256).hexdigest()
    return f"{exp_ts}:{sig}"


def verify_ws_ticket(ticket: str | None, run_id: str) -> bool:
    """
    Validate short-lived ticket generated by create_ws_ticket().
    """
    secret = settings.admin_api_key.strip()
    if not (secret and ticket):
        return False
    try:
        exp_raw, provided_sig = ticket.split(":", 1)
        exp_ts = int(exp_raw)
    except (ValueError, TypeError):
        return False
    if exp_ts < int(time.time()):
        return False
    payload = f"{run_id}:{exp_ts}".encode("utf-8")
    expected_sig = hmac.new(secret.encode("utf-8"), payload, hashlib.sha256).hexdigest()
    return hmac.compare_digest(provided_sig, expected_sig)
